[package]
name = "lru_cache_macros"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6"
lru_cache = {path = "/home/tyler/programming/projects/rust/lru_cache"}

[dependencies.proc-macro2]
version = "0.4"
features = ["nightly"]

[dependencies.syn]
version = "0.15"
features = ["full", "extra-traits"]

[lib]
proc-macro = true